services:
  Postgres:
    container_name: database_postgres
    image: postgres
    ports:
      - ${DB_POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_POSTGRES_NAME}
      - POSTGRES_USER=${DB_POSTGRES_USER_NAME}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASS}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
  Redis:
    depends_on:
      - Postgres
    container_name: database_redis
    image: redis/redis-stack-server:latest
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker/redis:/data