services:
  Postgres:
    container_name: database_postgres
    image: postgres
    ports:
      - ${DB_POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_POSTGRES_NAME}
      - POSTGRES_USER=${DB_POSTGRES_USER_NAME}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASS}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data